try {
  throw Error('AIUTOOOOOO!')
} catch(e) {
  console.log(e)
}



